server:
  port: 8080 # Flask 포트와 동일하게 설정

spring:
  # H2 데이터베이스 설정 (SQLite 대체)
  datasource:
    url: jdbc:h2:file:./db;AUTO_SERVER=TRUE # 파일 기반 DB로 설정 (서버 재시작해도 데이터 유지)
    driverClassName: org.h2.Driver
    username: sa
    password:

  # JPA (SQLAlchemy 대체) 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # 애플리케이션 시작 시 DB 스키마 자동 업데이트
    show-sql: true # 실행되는 SQL 쿼리를 로그에 표시

  # H2 콘솔 활성화 (웹 브라우저에서 DB 확인 가능, 주소: http://localhost:8080/h2-console)
  h2:
    console:
      enabled: true
      path: /h2-console

  web:
    resources:
      # 이 설정이 정확히 추가되었는지 확인!
      static-locations: classpath:/static/dist/


# Rate Limiting 설정 (Flask-Limiter 대체)
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      # 도서 목록 조회 API에만 제한 적용
      url: /api/books
      method: GET
      rate-limits:
        - bandwidths:
            # 1분당 30회 요청 제한
            - capacity: 30
              time: 1
              unit: minutes